Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Exclude:
    - 'lib/eye/checker/http.rb'
    - 'lib/eye/checker/socket.rb'
    - 'lib/eye/cli/server.rb'
    - 'lib/eye/dsl/opts.rb'
    - 'lib/eye/process/commands.rb'
    - 'lib/eye/process/monitor.rb'
    - 'lib/eye/process/scheduler.rb'
    - 'lib/eye/trigger/flapping.rb'
    - 'spec/process/start_spec.rb'
    - 'spec/spec_helper.rb'

Style/RedundantSelf:
  Enabled: false

Metrics/MethodLength:
  Max: 45

Metrics/ModuleLength:
  Max: 234

Metrics/PerceivedComplexity:
  Max: 29

Metrics/CyclomaticComplexity:
  Max: 26

Metrics/ClassLength:
  Max: 183

Metrics/BlockNesting:
  Max: 5

Metrics/AbcSize:
  Max: 83

Lint/RescueException:
  Exclude:
    - 'lib/eye/checker/socket.rb'
    - 'lib/eye/controller/load.rb'
    - 'lib/eye/logger.rb'
