Lint/LiteralInInterpolation:
  Exclude:
    - 'lib/eye/notify/jabber.rb'
    - 'lib/eye/notify/slack.rb'
    - 'lib/eye/process/commands.rb'

Lint/HandleExceptions:
  Exclude:
    - 'lib/eye/cli.rb'
    - 'lib/eye/server.rb'
    - 'lib/eye/system_resources.rb'

Style/RescueModifier:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/Void:
  Exclude:
    - Rakefile
    - bin/loader_eye
    - lib/eye/controller.rb

Lint/Eval:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Next:
  Exclude:
    - 'examples/processes/sample.rb'
    - 'lib/eye/config.rb'
    - 'lib/eye/controller/send_command.rb'
